---
title: "Relaxing the Assumptions of Knockoffs by Conditioning"
author: 
- name: Dongming Huang and Lucas Janson
date: 
output: 
  html_document:
    theme: flatly
bibliography: reference.bib
biblio-style: apalike
---
```{r setup, include=FALSE}
#theme: flatly,cosmo,yeti,cerulean,sandstone,paper,united,readable,spacelab,simplex,lumen
```

Generating conditional knockoffs is one way to generate valid model-X knockoffs without knowing the exact distribution of the covariates. This website contains some examples of generating conditional knockoffs for general multivariate Gaussian models, (high-dimensional) Gaussian graphical models, and discrete graphical models. These examples are used as numerical illustrations in Section 3 of Huang and Janson, 2019 ([PDF](url?)) . The source code used on this website can be found [here](url?).

******

## Introduction
Model-X knockoffs performs variable selection while controlling the false discovery rate. It relies on no assumptions on the conditional distribution of the response, but requires knowing the true distribution of the covariates. More information can be found [here](https://web.stanford.edu/group/candes/knockoffs/index.html)

Conditional knockoffs relax the requirement of model-X knockoffs by allowing the distribution of covariates to be known only up to a family of distributions, or model. Efficient algorithms to generate conditional knockoffs are established and proved to be valid in [Huang and Janson, 2019](url?). 

*****
## Reference
<span style="color:white"> cite [@DH-LJ:2019a] </span>
